#!/bin/bash
time=$(date +%I)
count=0
while [ "$count" -lt "$time" ]; do
        echo "No chime"

        let count=count+1
done
sleep 1
minute=$(date +%M)
if [[ $minute -gt 0 && $minute -le 19 ]]; then
     echo "No chime"
elif [[ $minute -gt 20 && $minute -le 39 ]]; then
        echo -ne "\a"
elif [[ $minute -gt 40 && $minute -lt 59 ]]; then
        echo -ne "\a"
        sleep 1
        echo -ne "\a"
else
        echo "No Chime"
fi
